graphql_error_logger/__init__.py,sha256=lgLh4dXqiWgOQcMCCSXIoAanfGfsUjQ0RNyo5goMd9U,1602
graphql_error_logger-0.0.3.dist-info/LICENSE,sha256=GKc7Shh3Wj8PTqkgijRaGRBFC_8cCSkj3WmIjYHkmbQ,1069
graphql_error_logger-0.0.3.dist-info/METADATA,sha256=7eLCtnXvZSmyoHzASRz0MCfPjkE4kjmXgAY0PDzf3l4,2524
graphql_error_logger-0.0.3.dist-info/WHEEL,sha256=g4nMs7d-Xl9-xC9XovUrsDHGXt-FT0E17Yqo92DEfvY,92
graphql_error_logger-0.0.3.dist-info/top_level.txt,sha256=jxO1ltpc6vWfqhRchvEZdXBRp9QxzQrDrOnfx_3PU90,21
graphql_error_logger-0.0.3.dist-info/RECORD,,
